version: "3.8"
services:
  arangodb:
    image: arangodb:3.7.3
    # Uncomment to use web interface in development
    # ports:
    #   - 8529:8529
    volumes:
      - arangodb_data:/var/lib/arango
    environment:
      ARANGO_NO_AUTH: 1

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #todo: check if the sock proxy is still required when using KAFKA_ADVERTISED_LISTERNERS. Xref: https://github.com/wurstmeister/kafka-docker/wiki/Connectivity

  arangodb-test:
    image: arangodb:3.7.3
    tmpfs: /var/lib/arango
    restart: always
    environment:
      ARANGO_NO_AUTH: 1

  core: &core
    build: .

  spider:
    <<: *core
    environment:
      URL_FILE: "data/test-urls.txt"
    command: ["scrapy", "crawl", "web"]

  cc-spider:
    <<: *core
    environment:
      URL_FILE: data/wikipedia_urls.csv
    command: ["scrapy", "crawl", "common_crawl_table_parser"]

  test:
    <<: *core
    command: ["python", "-m", "pytest"]
    environment:
      ARANGO_HOST: http://arangodb-test:8529
    depends_on:
      - arangodb-test

  lint:
    <<: *core
    environment:
      REQUIRED_QUALITY: 9
    command: ["pipenv", "run", "lint"]

volumes:
  arangodb_data:
