version: "3.8"
services:
  arangodb:
    image: arangodb:3.7.3
    # Uncomment to use web interface in development
    # ports:
    #   - 8529:8529
    volumes:
      - arangodb_data:/var/lib/arango
    environment:
      ARANGO_NO_AUTH: 1

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    build:
      context: kafka/
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:2:1" # name:partition:replicas
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      EXTRA_ARGS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7099:/usr/app/prom-jmx-agent-config.yml

  arangodb-test:
    image: arangodb:3.7.3
    tmpfs: /var/lib/arango
    restart: always
    environment:
      ARANGO_NO_AUTH: 1

  core: &core
    build: .

  spider:
    <<: *core
    environment:
      URL_FILE: "data/test-urls.txt"
      FOLLOW_LINKS: "false" # "true" for deep crawls
    command: ["scrapy", "crawl", "web"]

  cc-spider:
    <<: *core
    environment:
      URL_FILE: data/wikipedia_urls.csv
    command: ["scrapy", "crawl", "common_crawl_table_parser"]

  test:
    <<: *core
    command: ["python", "-m", "pytest"]
    environment:
      ARANGO_HOST: http://arangodb-test:8529
    depends_on:
      - arangodb-test

  schema_test:
    <<: *core
    command: ["scripts/schema_test.sh"]

  lint:
    <<: *core
    environment:
      REQUIRED_QUALITY: 9
    command: ["pipenv", "run", "lint"]

volumes:
  arangodb_data:
