version: "3.8"
services:
  core: &core
    build: .

  spider:
    <<: *core
    environment:
      URL_FILE: "data/test-urls.txt"

  test:
    <<: *core
    command: ["python", "-m", "unittest", "discover", "./test"]

  lint:
    <<: *core
    environment:
      REQUIRED_QUALITY: 9
    command: ["pipenv", "run", "lint"]
