version: "3.8"
services:
  core: &core
    build: .
    environment:
      URL_FILE: "data/wikipedia_urls.csv"

  spider:
    <<: *core
    command: ["scrapy", "crawl", "table_parser"]

  test:
    <<: *core
    command: ["python", "-m", "unittest", "discover", "./test"]

  lint:
    <<: *core
    environment:
      REQUIRED_QUALITY: 9
    command: ["pipenv", "run", "lint"]
