name: Python application

on: push

jobs:
  lint:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build core container
        run: docker-compose build core
      - name: Run linting
        run: docker-compose run lint
      - name: Run unit tests
        run: scripts/test_e2e.sh
      - name: Run integration test
        run: docker-compose run spider
